## This file defines all environment parameters used by the tool

# You need to put the necessary LSF installation files in the direcotry below. The files include
# <lsf_version>_lsfinstall_linux_x86_64.tar.Z
# <lsf_version>_linux2.6-glibc2.3-x86_64.tar.Z
# entitlement file
# floweditor has been put into PSS package
INSTALL_PACKAGE_DIR_FOR_LSF913="/Users/cwwu/docker/Project/P2-AutoInstall/Raw_Packages/LSF9.1.3/OriginalPackage"
INSTALL_PACKAGE_DIR_FOR_LSF101="/Users/cwwu/docker/Project/P2-AutoInstall/Raw_Packages/LSF10.1/OriginalPakcage"
INSTALL_PACKAGE_DIR_FOR_SAS_PSS91="/Users/cwwu/docker/Project/P2-AutoInstall/Raw_Packages/PPM/sas_pss9.1"
INSTALL_PACKAGE_DIR_FOR_SAS_PSS81="/Users/cwwu/docker/Project/P2-AutoInstall/Raw_Packages/PPM/sas_pss8.1"

INSTALL_PACKAGE_DIR_FOR_DM913="/Users/cwwu/docker/Project/P2-AutoInstall/Raw_Packages/DM/DM9.1.3"


# LSF spk files directory
SPK_DIR_FOR_LSF913="/Users/cwwu/docker/Project/P2-AutoInstall/Raw_Packages/LSF9.1.3/SPK/spk8/"
SPK_DIR_FOR_LSF101="/Users/cwwu/Docker/Project/P2-AutoInstall/Raw_Packages/LSF10.1/SPK/spk3"



# The image file that you choose to create docker containers
IMAGE="ubuntu:17.04.v4"
IMAGE4SAS="ubuntu:17.04.v4"

