#!/bin/bash

if [ ! $1 ]; then
	echo -e "Wrong command input! \n"
	echo -e "dshutdown usage:\n"
	echo -e "dshutdown [all | idxxx | hostname] \n"
	echo "Exit..."
	exit
fi

if [ $1 = "-h" ]; then
	echo -e "dshutdown usage:\n"
	echo -e "dshutdown [all | idxxx | hostname] \n"
	exit
fi

if [ $1 = "all" ]; then
#docker stop $(docker ps -a -q)
#	docker rm -v $(docker ps -a -q)
	echo "Shutting down following hosts:"
	docker stop $(docker ps --format '{{.Names}}')

else
	echo "Shutting down following hosts:"
	
	for node in $*
	do		
		docker stop $(docker ps --format '{{.Names}}' | grep $node)
	done

fi
